version: '3'

services:
  web:
    image: ${IMAGE_NAME}:${BUILD_NUMBER}
    ports:
      - "8088:8088"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    container_name: dart-ui-image-dev
    restart: always


